vich_uploader:
    db_driver: orm

    mappings:
        category_image:
            uri_prefix: /uploads/categories
            upload_destination: '%kernel.project_dir%/public/uploads/categories/'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
        team_image:
            uri_prefix: /uploads/team
            upload_destination: '%kernel.project_dir%/public/uploads/team/'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
        slider_image:
            uri_prefix: /uploads/slider
            upload_destination: '%kernel.project_dir%/public/uploads/slider/'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer
        logo_image:
            uri_prefix: /uploads/logo
            upload_destination: '%kernel.project_dir%/public/uploads/logo/'
            namer: Vich\UploaderBundle\Naming\SmartUniqueNamer

